<center>
<div style="margin-top:50px;">
	<font color="#B0B0B0" size="1">
		<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="http://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under the <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International Lizenz</a>.
		<br><br>
		glESCapsViewer OpenGL ES capabilities database - © 2011-2015 by <a href="http://www.saschawillems.de/" target="blank">Sascha Willems</a><br>
		OpenGL is a registered trademark and the OpenGL ES logo is a trademark of Silicon Graphics Inc. used by permission by Khronos.
	</font>
</div>
</center>
